### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [yolosec/routerkeygenAndroid#1]
Are you ok to try to add this app in [F-Droid](https://f-droid.org/), a Store with only free and open source apps?

It looks like you already have a no gapps build flavor, which is great 👍

**Comment by ph4r05** [comment]
Ok feel free to add it

**Comment by Poussinou** [comment]
A `Request For Packaging` is now open [here](https://gitlab.com/fdroid/rfp/issues/521). It may take a lot of time to include your app, since all F-Droid packagers are busy. You can have a look at the documentation if you want to write yourself the small file to include your app in the repo, it isn't that complicated.

**Comment by Poussinou** [comment]
@ph4r05 What is this blob used for?

> https://github.com/yolosec/routerkeygenAndroid/blob/master/android/mm-ad-sdk/mm-ad-sdk.aar

Is it possible to remove it, rebuilt it from source code or replace it with a Gradle dependency from a well-known Maven repo?

**Comment by ph4r05** [comment]
I will check and let you know. This repo is a fork so it may be some ad artifact.

**Comment by Rudloff** [comment]
The app seems to build and work fine without `android/mm-ad-sdk/mm-ad-sdk.aar`. Maybe it could removed from the repository if you don't use it?

**Comment by ph4r05** [comment]
sorry for long delay. `mm-ad-sdk` can be removed, I just committed the removal.

**Comment by Rudloff** [comment]
The app is now in F-Droid so this issue can be closed: https://f-droid.org/packages/net.yolosec.routerkeygen2/
